# version 1.0.0

services:
  bot:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB__URL=${DB__URL}
    volumes:
      - /var/logs:/var/logs
      - /var/alembic:/app/alembic/versions
    container_name: bot
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.000'  # Устанавливает неограниченное использование CPU
          memory: '0'    # Устанавливает неограниченное использование памяти

    restart: always
  db:
    image: postgres:15.1-alpine
    container_name: db
    env_file:
        - .env
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    restart: always
